const lang = {
  en: {
    sign_in: "Sign In",
    sign_out: "Sign Out",
    sign_up: "Sign Up",
    browse: "Browse",
    my_profile: "My Profile",
    my_favourites: "My Favourites",
    search_placeholder: "Movies, Titles, Genres",
    newToNetflix: "New to Netflix? Sign up now.",
    password: "Password",
    email: "Email Address",
    name: "Full Name",
    alreadyAcc: "Already have an account? Sign in.",
    play: "Play",
    more_info: "More Info",
    user_information: "User Information",
    language_preference_title: "Language Preferences",
    language: "Language",
    subscription_info: "Subscription Info",
    plan_label: "Plan",
    price_label: "Price",
    next_billing_date: "Next Billing Date",
    status_label: "Status",
    getstarted_title: "Get Started",
    homepage_main_title: "Unlimited movies, TV shows and more",
    homepage_title: "Watch anywhere. Cancel anytime.",
    homepage_subtitle:
      "Ready to watch? Enter your email to create or restart your membership.",
    add_favourites: "Add to My Favourites",
    remove_favourites: "Remove from My Favourites",
    show_description: "See Movie Details",
    hide_description: "Hide Movie Details",
  },
  hi: {
    sign_in: "दाखिल करना",
    sign_out: "साइन आउट",
    sign_up: "साइन अप करें",
    browse: "ब्राउज़",
    my_profile: "मेरी प्रोफाइल",
    my_favourites: "मेरा पसंदीदा",
    search_placeholder: "फ़िल्में, शीर्षक, शैलियाँ",
    newToNetflix: "नेटफ्लिक्स पर नए हैं? अभी साइन अप करें।",
    password: "पासवर्ड",
    email: "मेल पता",
    name: "पूरा नाम",
    alreadyAcc: "क्या आपके पास पहले से एक खाता मौजूद है? साइन इन करें।",
    play: "चलाएं",
    more_info: "और जानकारी",
    user_information: "यूजर जानकारी",
    language_preference_title: "भाषा प्राथमिकताएँ",
    language: "भाषा",
    subscription_info: "सदस्यता जानकारी",
    plan_label: "प्लान",
    price_label: "कीमत",
    next_billing_date: "अगली बिलिंग तिथि",
    status_label: "योजना की स्थिति",
    getstarted_title: "शुरू करें",
    homepage_main_title: "असीमित फिल्में, टीवी शो और बहुत कुछ",
    homepage_title: "कहीं भी देखें। कभी भी रद्द करें।",
    homepage_subtitle:
      "देखने के लिए तैयार हैं? अपनी सदस्यता शुरू करने या फिर से चालू करने के लिए अपना ईमेल दर्ज करें।",
    add_favourites: "मेरे पसंदीदा में जोड़ें",
    remove_favourites: "पसंदीदा से हटाएं",
    show_description: "फिल्म विवरण देखें",
    hide_description: "मूवी विवरण छिपाएँ",
  },
  te: {
    sign_in: "సైన్ ఇన్ చేయండి",
    sign_out: "సైన్ అవుట్ చేయండి",
    sign_up: "సైన్ అప్ చేయండి",
    browse: "బ్రౌజ్",
    my_profile: "నా ప్రొఫైల్",
    my_favourites: "నా ఇష్టమైనవి",
    search_placeholder: "సినిమాలు, శీర్షికలు, శైలులు",
    newToNetflix: "నెట్‌ఫ్లిక్స్‌కు కొత్తవారా? సైన్ అప్ చేయండి",
    password: "పాస్వర్డ్",
    email: "ఇమెయిల్ చిరునామా",
    name: "పూర్తి పేరు",
    alreadyAcc: "ఖాతా ఉందా? సైన్ ఇన్ చేయండి",
    play: "ప్లే చేయండి",
    more_info: "మరింత సమాచారం",
    user_information: "వినియోగదారు సమాచారం",
    language_preference_title: "భాషా ప్రాధాన్యతలు",
    language: "భాష",
    subscription_info: "సబ్‌స్క్రిప్షన్ సమాచారం",
    plan_label: "ప్లాన్",
    price_label: "ధర",
    next_billing_date: "తదుపరి బిల్లింగ్ తేదీ",
    status_label: "ప్లాన్ స్టేటస్",
    getstarted_title: "ప్రారంభించండి",
    homepage_main_title: "అనియమితమైన సినిమాలు, టీవీ షోలు మరియు మరిన్నివి",
    homepage_title: "ఏక్కడైనా చూడండి. ఎప్పుడైనా రద్దు చేయండి.",
    homepage_subtitle:
      "చూడడానికి సిద్ధంగా ఉన్నారా? మీ మెంబర్‌షిప్ ప్రారంభించడానికి లేదా పునఃప్రారంభించడానికి మీ ఇమెయిల్ నమోదు చేయండి.",
    add_favourites: "నా ఇష్టాలలో చేర్చండి",
    remove_favourites: "నా ఇష్టాల నుండి తీసేయండి",
    show_description: "సినిమా వివరాలు చూడండి",
    hide_description: "సినిమా వివరాలు దాచండి",
  },
};

export default lang;
